[package]
name = "runtime"
version = "0.1.1"
edition = "2021"

[dependencies]
sysinfo = "0.36.1"
chrono = { version = "0.4.34", features = ["serde"] }
clap = { version = "4.5.4", features = ["derive"] }
colored = "3.0.0"
crossterm = "0.29.0"
indicatif = "0.18.0"

[lib]
path = "src/lib.rs"
